#!/bin/bash
FILE_NAME=$1
if [ -z $1 ]
then
	echo "This command is meant for compiling, running, and generating some info."
	echo "error: missing filename option, usage: '$0 filename.c'" >&2
	exit 1
fi
echo "*.${FILE_NAME}.log"

rm a.out
rm *.${FILE_NAME}.log
gcc -g3 "./${FILE_NAME}"
objdump -Mintel -d ./a.out > objdump.${FILE_NAME}.log
strace --output strace.${FILE_NAME}.log ./a.out
# nm defaults to a.out
nm -D > nm.-D.${FILE_NAME}.log
nm > nm.${FILE_NAME}.log
ls -l *.${FILE_NAME}.log
echo yep.
